### ISSUE TITLE
TOC not work

### ISSUE THREAD

**Issue by vonsago** [PaulieScanlon/gatsby-theme-terminal#11]
I try to add table of contents in my blog. But it failed.
https://www.gatsbyjs.org/packages/gatsby-remark-table-of-contents/

**Comment by PaulieScanlon** [comment]
Hey @vonsago i'm gonna need a little more info. Are you able to provide a link to your repo?

**Comment by vonsago** [comment]
Thanks your response.
repo:https://github.com/vonsago/vongola.github.io/tree/gy-page
this test post:https://github.com/vonsago/vongola.github.io/blob/gy-page/src/posts/2020/01/%E6%B5%8B%E8%AF%95.mdx

reference:https://www.gatsbyjs.org/packages/gatsby-remark-table-of-contents/
