### ISSUE TITLE
Make gatsby-plugin-google-fonts plugin optional

### ISSUE THREAD

**Issue by mshick** [PaulieScanlon/gatsby-theme-terminal#15]
Would it be possible to make the Google Fonts plugin optional, or remove it entirely? I'd like to use a different font, and my only option to drop the Inconsolata load seems to be forking the theme. 

Love this theme's look and approach, thanks!

**Comment by PaulieScanlon** [comment]
@mshick just off the top of my head, what happens if you shadow gatsby.config, I think you’ll then be able to modify the use of google fonts
