### ISSUE TITLE
Make gatsby-plugin-theme-ui optional

### ISSUE THREAD

**Issue by mshick** [PaulieScanlon/gatsby-theme-terminal#16]
Sorry to bomb you, related to my other issue, wondering if you'd consider making the theme-ui plugin optional. I realize that's the standard theme-ui plugin, but the blocking approach they take to support color modes can have a big impact on Lighthouse (and possibly other) profilers. See [issue](https://github.com/system-ui/theme-ui/issues/980). 

I realize you rely heavily on theme-ui, so for most folks they could install the plugin as a peer. In my case, I could import your theme and present to my own site's `wrapRootElement` implementation.

**Comment by PaulieScanlon** [comment]
@mshick Hey, thanks for you interest in the project. Unfortunately I don’t think I’ll be able to make Theme UI optional as all of the theme styles depend on it. Sorry about that!
