### ISSUE TITLE
Posts not sorted by date

### ISSUE THREAD

**Issue by manparvesh** [PaulieScanlon/gatsby-theme-terminal#6]
Hi,
Thanks for putting this amazing theme on Github! I am trying to port my website to this theme and noticed that the posts are not sorted by date. I am not familiar with React and Gatsby, but I tried making a few changes in the code but failed. 

Things that I tried:
1. in posts.mdx
```diff
posts
+        .sort((a, b) =>  new Date(a.date) - new Date(b.date))
        .map((edge, index) => {
```

2. in useAllMdx.js
```diff
allMdx {
      allMdx(
        filter: {
          frontmatter: {
            title: { ne: "dummy" }
            navigationLabel: { ne: "dummy" }
            status: { ne: "draft" }
          }
          fields: { owner: { eq: "source" } }
+          sort: { fields: [frontmatter___date], order: DESC }
        }
```

**Comment by PaulieScanlon** [comment]
Hey @manparvesh you shouldn't need to change `useAllMdx.js` as you can get at the date returned from your `.mdx`

I've done something similar on my commercial portfolio https://www.pauliescanlon.io/#open-source

Something like this should work for you. and the date format in frontmatter should be eg; 
`date: 2018-11-31` or `yyyy-mm-dd`

```javascript
{
posts
.sort((a, b) => new Date(b.node.frontmatter.date) - new Date(a.node.frontmatter.date))
.map((edge, index) => {
...
`

**Comment by manparvesh** [comment]
@PaulieScanlon thanks! That works.
Thanks again for open-sourcing this great theme.
